import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import "./globals.css";
import NavBar from "@/components/nav-bar";

import { cn } from "@/lib/utils";
import { CounterStoreProvider } from "@/providers/counter-store-provider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased relative",
          fontSans.variable
        )}
      >
        <CounterStoreProvider>
          <NavBar />
          {children}
        </CounterStoreProvider>
      </body>
    </html>
  );
}
